<?php

namespace App\Services\Adapters;

use App\Contracts\EmbeddingEngine;
use Laravel\Ai\Embeddings;

class OllamaEmbeddingAdapter implements EmbeddingEngine
{
    /**
     * Generate an embedding vector for the given text using Ollama (via laravel/ai).
     *
     * @return array<float>
     */
    public function generate(string $text): array
    {
        return $this->generateBatch([$text])[0] ?? [];
    }

    public function generateBatch(array $texts): array
    {
        return Embeddings::for($texts)
            ->generate()
            ->embeddings;
    }

    /**
     * Get the dimensions of the vectors generated by the nomic-embed-text model.
     */
    public function getDimensions(): int
    {
        return 768;
    }
}
