<?php

namespace App\Services\Adapters;

use App\Contracts\EmbeddingEngine;
use Laravel\Ai\Embeddings;

class OllamaEmbeddingAdapter implements EmbeddingEngine
{
    /**
     * Generate an embedding vector for the given text using Ollama (via laravel/ai).
     *
     * @return array<float>
     */
    public function generate(string $text): array
    {
        $response = Embeddings::for([$text])
            ->generate();

        return $response->first() ?? [];
    }

    /**
     * Get the dimensions of the vectors generated by the nomic-embed-text model.
     */
    public function getDimensions(): int
    {
        return 768;
    }
}
