<?php

namespace App\Contracts;

interface EmbeddingEngine
{
    /**
     * Generate an embedding vector for the given text.
     *
     * @return array<float>
     */
    public function generate(string $text): array;

    /**
     * Generate embedding vectors for multiple texts.
     *
     * @param  array<string>  $texts
     * @return array<array<float>>
     */
    public function generateBatch(array $texts): array;

    /**
     * Get the dimensions of the vectors generated by this engine.
     */
    public function getDimensions(): int;
}
