<?php

namespace App\Contracts;

interface EmbeddingEngine
{
    /**
     * Generate an embedding vector for the given text.
     *
     * @return array<float>
     */
    public function generate(string $text): array;

    /**
     * Get the dimensions of the vectors generated by this engine.
     */
    public function getDimensions(): int;
}
